// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import Carousel from "stimulus-carousel";
application.register("carousel", Carousel);

import HelloController from "./hello_controller";
application.register("hello", HelloController);

import PreviewsController from "./previews_controller";
application.register("previews", PreviewsController);

import SidebarController from "./sidebar_controller";
application.register("sidebar", SidebarController);

import ModalController from "./modal_controller";
application.register("modal", ModalController);
